### ISSUE TITLE
Full Screen option not available for android

### ISSUE THREAD

**Issue by hashimks** [Xamarians/MediaPlayer#1]
Hello,
This is a simple and nice video player plugin. However I found an issue with respect to no full screen option in the built in control of the player for android mobile. 

Also another issue is, if i try to bind a list of videos on the list view of this video player, on scrolling the list view the controls of video will be scrolling over the list. This is also occurring in android. If this gets fixed, this will be the best one.

**Comment by Xamarians** [comment]
Hi Hashmiks,

Thanks for your feedback. We will look into this and will get back to you by end of this week.

**Comment by Xamarians** [comment]
Hello Hasmiks,
We have added full screen behavior in android player, Update library to see changes. 

For your second issue please provide some screen shots to help you better.

**Comment by hashimks** [comment]
Hello Team,

Thanks for your response. I have not get the nuget update for the library. It is still 1.0.0.

Regarding the screenshot, the control is scrolling over the list and then comes back to the correct list item. This is happening within seconds so i am not able to take a screenshot.

**Comment by hashimks** [comment]
Hello... I checked today also for the update and it is not available. The latest in nuget is still 1.0.0. Can you please let me know the updates? Thanks for your wonderful plugin

**Comment by hashimks** [comment]
Hello, 

I managed to get the control dislocation screenshot as well. I could see that in a scrollable page, i have the video player with two text areas. While playing the video and scrolling down to the text area, the control will change its position and it disappears from there after sometime and later it can be seen at the proper place.  Here is the screenshot.

![controlmislocation](https://user-images.githubusercontent.com/30616681/29116114-7a415f08-7d17-11e7-9fdf-b56bac81fd57.jpg)

**Comment by hashimks** [comment]
hello??

**Comment by Xamarians** [comment]
Hi Hashimks

We are working on your issues will get back to you soon.

**Comment by hashimks** [comment]
Hi team,,, Any updates on this?

**Comment by Xamarians** [comment]
Hello Hashimks,

we are able to reproduce the bug and working on it. Hopefully you will see the new updates by tomorrow.

**Comment by hashimks** [comment]
Thats a good news.. Thanks a lot. It will be better if you update the nuget package, so that i can update my project as well.

**Comment by Xamarians** [comment]
Hi hashimks 

We have released the updated library on nuget which will fixed all your issues.
