### ISSUE TITLE
Demo App video file location on Android

### ISSUE THREAD

**Issue by jonathan-jd4software** [Xamarians/MediaPlayer#16]
Looking at the demo app it uses a hard coded media file 1131482142593576400bd.mp4
Where should this file be in the android demo?  It exists in the iOS project in the Resources folder, but not in the Android project.

**Comment by Xamarians** [comment]
Hi jonathan

This media player will not play video from local resource file. So you need to pass video url to play video.

**Comment by jonathan-jd4software** [comment]
It is possible to get the media player to play a local resource file.  Assuming the same media file is to be used "1131482142593576400bd.mp4"

iOS
Place the mp4 file in Resources folder.
Set the source of the Media player with the result of this:

`Path.Combine(NSBundle.MainBundle.BundlePath, "1131482142593576400bd.mp4");`

Android
Place the mp4 file in a "raw" subfolder of the Resources folder
Set the source of the Media player with the result of this:

`"android.resource://" + Android.App.Application.Context.PackageName + "/" + Resource.Raw.1131482142593576400bd`
