### ISSUE TITLE
Problem with fullscreen

### ISSUE THREAD

**Issue by hauphidao** [Xamarians/MediaPlayer#17]
when i play video with fullscreen option and my device rotation to horizontal, but when i press hard back button on my device. my device dont rotation to vertical. please help me how to fix it...thanks

**Comment by prom3theu5** [comment]
I just took their custom renderer and removed both the force orientation lines of code.
I actually think it's better to just allow the user to rotate their device if they want the screen to rotate.

Then I added a Bindable Property for ForceFullscreen

**Comment by hauphidao** [comment]
how can i do that, can you help me ??
