### ISSUE TITLE
Additional Track Information...

### ISSUE THREAD

**Issue by kardall** [Xamarians/MediaPlayer#2]
So I have been looking through demos and I don't see this, so maybe it's not implemented yet but...

Any way to add things like the title, additional information. I am using it as an audio player to stream audio where I do have things like Artist, Title, Genre, Album etc. But I don't see any way to display these things on the player, only the duration.

**Comment by Xamarians** [comment]
Hi kardall,
Thanks for writing us. 
Actually above feature are not supported by audio player, we have noted your suggestions and will integrate your suggestions soon.
