### ISSUE TITLE
Media Player Keeps Playing After the ContentPage is Closed

### ISSUE THREAD

**Issue by kenneymyers** [Xamarians/MediaPlayer#20]
I am having a problem where the Media player won't stop playing the video.  I have tried calling the stop method before the content page closes and that is not working.  Is there a way to stop it for sure and/or dispose of it properly?

**Comment by kenneymyers** [comment]
This only appears to happen if you autoplay the video.  However, it also doesn't seem to be disposed of properly.

**Comment by Xamarians** [comment]
Hi @longhornleads, I think the problem is you are calling pause() and Stop() method before video player object is created just make sure its initialized before calling stop() or pause() method.
