### ISSUE TITLE
Loading video taking time

### ISSUE THREAD

**Issue by hashimks** [Xamarians/MediaPlayer#3]
Hello Team,

I have another issue to address here. I have the player with AutoPlay set to true and I am setting the source of the player to the below link.

https://s3.ap-south-1.amazonaws.com/businessdebatedevbucket/5131480304817981070bd.mp4

Here the player is taking long long time to play this video. The video size is around 80MB. Is there any way to improve it like kind of part by part buffering? Can you help me in this as well?

**Comment by Xamarians** [comment]
Hi,

Thanks for asking.
Buffering concept is already implemented in video player to play large video. The player takes long time due to slow internet connection and large video size.
