### ISSUE TITLE
Video player is not showing in iPhone

### ISSUE THREAD

**Issue by hashimks** [Xamarians/MediaPlayer#4]
Hello Team,

Today only i took a build of iphone with this media player and I could see the player is not showing up. I have tested in two iPhones.
1. iPhone 6 - iOS 10.2.1 ---- the video player is not showing up.
2. iPhone 5c - iOS 9.2.1 ---- the video player is showing up with the seekbar, but the play is kind of disabled and no sound. I have set the autoplay as true.

Note that, i tried this with simulator and is working fine. Can you please check this asap? I m stuck here :(

![videoplay](https://user-images.githubusercontent.com/30616681/29709757-473bc2ce-89ab-11e7-853b-5f4f65060fc8.png)

**Comment by hashimks** [comment]
Hello, Please help me on this. I am stuck here and not able to go forward :(

**Comment by Xamarians** [comment]
it seems video was not loaded. Please make sure you have set correct source and also below settings in info.plist file.
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsArbitraryLoads</key>
<true/>
</dict>

**Comment by hashimks** [comment]
i have already set that and issue is there..

<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>

note that it is working well in simulator.

**Comment by hashimks** [comment]
Please help..

**Comment by Xamarians** [comment]
Hi hasmiks,

We are able to play first video here and second video url is broken its not working in browser too.

**Comment by hashimks** [comment]
Hi,

Can you please share me the sample app u tried, so that i can check it here whether i missed anything or not? It will really helpful

**Comment by hashimks** [comment]
@Xamarians Hello can u pls share?

**Comment by Xamarians** [comment]
Hi hashimks,

We have checked the sample video list you have posted here.It seems that problem is not in your code but the resolution of video. The resolution of first video is very less so we are able to play it, but the resolution of your second video is very high(2160*3840). It can support upto video of 1920*1080p in iphone 5 and 6/6+.
You can test your sample app with the video of 1920*1080p or less.

**Comment by hashimks** [comment]
@Xamarians Hello.. i have tried both the videos and not able to play. I just wanted to know whether i missed any configuration/settings. This is occurring only in devices and in iOS simulator it is working. If u can share the sample it will be really helpful.

**Comment by hashimks** [comment]
@Xamarians 
this is the latest video which is not getting played in iOS device

https://s3.amazonaws.com/hashimsbucket/5131484024127625850bd.mov

**Comment by Xamarians** [comment]
Hi hashimks,

There is a problem with your latest video . Your video have codecs of H.264 and AMR Narrowband. Over iOS4.3 or later, the AMR format is no longer supported for video. 
Video Codecs: H.264, H.263-1998 / H.263+, (VP8 coming soon…)
We are able to play that video by converting it through QuickTimePlayer app.

**Comment by hashimks** [comment]
@Xamarians Is it the audio format causing this issue? Is there any way in the app, we can convert it without using any other external apps?

**Comment by Xamarians** [comment]
Hi hashimks,
sorry, we don't have very much information on it. post your question on xamarin forums https://forums.xamarin.com to get more help.
