### ISSUE TITLE
Not able to Play flv video in Marshmallow

### ISSUE THREAD

**Issue by VinayGada** [Xamarians/MediaPlayer#7]
Am using this player to play live video of sites where our camera has installed.
Am able to play video in android version (V 5- Lollypop), and Nouget(7.0) but not able to play in marshmallow

**Comment by Xamarians** [comment]
Hi vinayGada

Thanks for writing us.
we are working on this problem and will let you know once done.

**Comment by VinayGada** [comment]
Thanx for your reply sir....
and am having the issue in iPhone also

**Comment by Xamarians** [comment]
Hi VinayGada 
Can you share us a video link that you are not able to play?

**Comment by VinayGada** [comment]
Could you please share your email Id,So that i can share the video link
