### ISSUE TITLE
Full Screen View on play button click

### ISSUE THREAD

**Issue by hashimks** [Xamarians/MediaPlayer#8]
Hello Team,

I am using Xamarians player in my project due to its good features and easiness. However I have a query which can be a new feature. Say I open a video in the video player, i can see the play button and on clicking the play button it will play. I can also see the full screen view option in the player to display it in full screen. Is there any way to implement the feature like on clicking the play button, the Xamarians player should play the video in full screen mode (a property).  It will be really helpful.

**Comment by Xamarians** [comment]
Hi hashimks

Thanks for writing us.
we have noted your suggestions and will integrate your suggestions soon.
